import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fb",
  },
  authShell: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  page: {
    width: "100%",
    maxWidth: 920,
    alignSelf: "center",
    gap: 12,
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  panel: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderColor: "#d8dee9",
    borderWidth: 1,
    borderRadius: 8,
    padding: 16,
    gap: 12,
  },
  centerBlock: {
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 24,
  },
  title: {
    color: "#111827",
    fontSize: 24,
    fontWeight: "700",
  },
  sectionTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "700",
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  bodyText: {
    color: "#374151",
    fontSize: 15,
    lineHeight: 22,
  },
  mutedText: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 19,
  },
  errorText: {
    color: "#b42318",
    fontSize: 14,
    lineHeight: 20,
  },
  successText: {
    color: "#067647",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#cfd6e4",
    borderRadius: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
    color: "#111827",
    fontSize: 15,
  },
  primaryButton: {
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: "#174ea6",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  secondaryButton: {
    minHeight: 40,
    borderWidth: 1,
    borderColor: "#b9c7dc",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: 12,
    backgroundColor: "#fff",
  },
  secondaryButtonText: {
    color: "#174ea6",
    fontSize: 14,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  tabBar: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    borderWidth: 1,
    borderColor: "#d8dee9",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 6,
  },
  tabButton: {
    minHeight: 38,
    minWidth: 110,
    flex: 1,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  tabButtonActive: {
    backgroundColor: "#174ea6",
  },
  tabText: {
    color: "#4b5563",
    fontSize: 14,
    fontWeight: "800",
  },
  tabTextActive: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "800",
  },
  segment: {
    flexDirection: "row",
    gap: 8,
  },
  segmentButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#cfd6e4",
    borderRadius: 8,
    alignItems: "center",
    paddingVertical: 10,
  },
  segmentButtonActive: {
    borderColor: "#174ea6",
    backgroundColor: "#edf4ff",
  },
  segmentText: {
    color: "#4b5563",
    fontWeight: "600",
  },
  segmentTextActive: {
    color: "#174ea6",
    fontWeight: "700",
  },
  summaryRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "space-between",
  },
  summaryItem: {
    minWidth: 120,
    flex: 1,
  },
  label: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  metric: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
  },
  notice: {
    borderWidth: 1,
    borderColor: "#f3c677",
    borderRadius: 8,
    backgroundColor: "#fff8eb",
    padding: 12,
    gap: 10,
  },
  noticeText: {
    color: "#8a4b0f",
    fontSize: 14,
    fontWeight: "600",
  },
  adminPanel: {
    borderColor: "#b9c7dc",
    backgroundColor: "#f8fbff",
  },
  adminBadge: {
    borderRadius: 999,
    backgroundColor: "#edf4ff",
    color: "#174ea6",
    fontSize: 12,
    fontWeight: "800",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  adminBlock: {
    minWidth: 240,
    borderWidth: 1,
    borderColor: "#d8dee9",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    padding: 12,
    gap: 10,
  },
  adminBlockTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  potGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  potCell: {
    minWidth: 80,
    flex: 1,
    borderWidth: 1,
    borderColor: "#d8dee9",
    borderRadius: 8,
    padding: 12,
  },
  potCount: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
  },
  playerTable: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    overflow: "hidden",
  },
  playerTableFrozenLayout: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
  },
  playerTablePinnedColumn: {
    flexShrink: 0,
    backgroundColor: "#ffffff",
  },
  playerTableScrollableColumn: {
    flex: 1,
    minWidth: 0,
  },
  playerTableScrollableContent: {
    minWidth: "100%",
  },
  playerTableScrollableRows: {
    minWidth: "100%",
  },
  playerTableRow: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
  },
  playerTableHeaderFixedRow: {
    height: 58,
  },
  playerTableDataRow: {
    height: 78,
  },
  tennisPlayerTableDataRow: {
    height: 104,
  },
  playerTableHeaderRow: {
    backgroundColor: "#f9fafb",
  },
  playerTableCell: {
    minHeight: 58,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#e5e7eb",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  playerTableHeaderCell: {
    alignSelf: "stretch",
  },
  playerTableDataCell: {
    alignSelf: "stretch",
  },
  playerTableCellEmpty: {
    backgroundColor: "#ffffff",
  },
  playerTableStatusCellActive: {
    backgroundColor: "#eef8f1",
  },
  playerTableStatusCellEliminated: {
    backgroundColor: "#fff1f1",
  },
  playerTableNameCell: {
    minWidth: 150,
    flex: 1.15,
  },
  playerTablePinnedNameCell: {
    width: 150,
    minWidth: 150,
    flex: 0,
  },
  playerTableTeamCell: {
    minWidth: 120,
    flex: 1,
  },
  tennisPlayerTableTeamCell: {
    width: 142,
    minWidth: 142,
    flex: 0,
  },
  playerTableTeamCellActive: {
    backgroundColor: "#eef8f1",
  },
  playerTableTeamCellEliminated: {
    backgroundColor: "#fff1f1",
  },
  playerTableTotalCell: {
    minWidth: 64,
    flex: 0.45,
    alignItems: "center",
  },
  playerTablePinnedTotalCell: {
    width: 64,
    minWidth: 64,
    flex: 0,
  },
  playerTableHeaderText: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "800",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  playerName: {
    flexShrink: 1,
    color: "#111827",
    fontSize: 15,
    fontWeight: "700",
    lineHeight: 20,
  },
  assignmentCellContent: {
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  tennisAssignmentCellContent: {
    width: "100%",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 3,
  },
  assignmentInfo: {
    alignSelf: "stretch",
    width: "100%",
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  assignmentText: {
    color: "#1f2937",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  assignmentTextEliminated: {
    color: "#a52a2a",
  },
  tennisNameWithFlag: {
    flex: 1,
    alignSelf: "stretch",
    width: "100%",
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
    overflow: "hidden",
  },
  tennisFlagIcon: {
    width: 18,
    height: 12,
    borderRadius: 2,
    backgroundColor: "#e5e7eb",
    flexShrink: 0,
  },
  tennisNeutralFlagIcon: {
    width: 18,
    height: 12,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  assignmentPointsBox: {
    alignSelf: "stretch",
    minWidth: 28,
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  assignmentPoints: {
    color: "#174ea6",
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 18,
    minWidth: 16,
  },
  emptyCellText: {
    color: "#9ca3af",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
  },
  playerTotalPoints: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
  },
  scoringRules: {
    marginTop: 12,
    gap: 4,
  },
  scoringRulesTitle: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  scoringRulesText: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 17,
  },
  pointsDetails: {
    marginTop: 12,
    borderTopWidth: 1,
    borderColor: "#e5e7eb",
    paddingTop: 12,
    gap: 10,
  },
  pointsSliderHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  pointsSliderButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: "#d8dee9",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  pointsSliderButtonDisabled: {
    opacity: 0.45,
  },
  pointsSliderButtonText: {
    color: "#174ea6",
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 26,
  },
  pointsSliderPlayerInfo: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  pointsDetailsPlayer: {
    gap: 6,
  },
  pointsDetailsPlayerName: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
  },
  pointsDetailsTeamList: {
    gap: 6,
  },
  pointsDetailsTeam: {
    minHeight: 54,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    backgroundColor: "#f9fafb",
    flexDirection: "row",
    alignItems: "stretch",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  pointsDetailsInfo: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    gap: 4,
  },
  pointsDetailsTeamName: {
    color: "#1f2937",
    fontSize: 12,
    fontWeight: "800",
  },
  pointsDetailsLineList: {
    gap: 2,
  },
  pointsDetailsTotal: {
    color: "#174ea6",
    fontSize: 14,
    fontWeight: "900",
  },
  pointsDetailsTotalBox: {
    minWidth: 32,
    flexShrink: 0,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  pointsDetailsText: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "600",
    lineHeight: 15,
  },
  teamColumns: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  teamColumn: {
    minWidth: 190,
    flex: 1,
    borderWidth: 1,
    borderColor: "#d8dee9",
    borderRadius: 8,
    padding: 10,
    gap: 10,
  },
  teamColumnHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  teamList: {
    gap: 6,
  },
  teamRow: {
    minHeight: 42,
    borderWidth: 1,
    borderColor: "#dbe5f3",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    paddingVertical: 7,
    paddingHorizontal: 8,
  },
  teamRowActive: {
    borderColor: "#d7ecd8",
    backgroundColor: "#f4fbf5",
  },
  teamRowEliminated: {
    borderColor: "#f4d4d4",
    backgroundColor: "#fff7f7",
  },
  teamRowAssigned: {
    borderColor: "#e5e7eb",
    backgroundColor: "#f3f4f6",
    opacity: 0.62,
  },
  teamName: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  teamNameActive: {
    color: "#17683a",
  },
  teamNameEliminated: {
    color: "#a52a2a",
  },
  teamNameAssigned: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  teamOwner: {
    color: "#6b7280",
    fontSize: 11,
    lineHeight: 15,
  },
  scheduleSliderHeader: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  scheduleSliderDate: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  scheduleSliderTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    lineHeight: 20,
    textAlign: "center",
  },
  scheduleSliderMeta: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
    textAlign: "center",
  },
  matchList: {
    gap: 6,
  },
  matchRow: {
    minHeight: 58,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  matchRowLive: {
    borderColor: "#fecaca",
    backgroundColor: "#fff7f7",
  },
  matchTimeColumn: {
    minWidth: 88,
    flexShrink: 0,
    gap: 2,
  },
  matchTime: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 18,
  },
  matchMeta: {
    color: "#6b7280",
    fontSize: 11,
    fontWeight: "700",
    lineHeight: 15,
    textTransform: "uppercase",
  },
  matchTeamsColumn: {
    flex: 1,
    minWidth: 0,
    flexShrink: 1,
    gap: 2,
  },
  matchTeams: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 19,
  },
  matchTeamOwner: {
    color: "#6b7280",
    fontWeight: "700",
  },
  matchTeamActive: {
    color: "#17683a",
  },
  matchTeamPending: {
    color: "#6b7280",
  },
  matchTeamEliminated: {
    color: "#a52a2a",
  },
  matchScoreBox: {
    minWidth: 68,
    minHeight: 36,
    flexShrink: 0,
    borderRadius: 8,
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  matchScore: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "800",
  },
  bracketScrollContent: {
    paddingVertical: 4,
    paddingRight: 10,
  },
  bracketBoard: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  bracketRoundColumn: {
    width: 222,
    flexShrink: 0,
  },
  bracketRoundTitle: {
    width: 184,
    height: 24,
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 18,
    textAlign: "center",
    textTransform: "uppercase",
  },
  bracketRoundMatches: {
    alignItems: "stretch",
    position: "relative",
  },
  bracketMatchWrap: {
    height: 72,
    flexDirection: "row",
    alignItems: "center",
  },
  bracketMatchCard: {
    width: 184,
    height: 72,
    borderWidth: 1,
    borderColor: "#dbe5f3",
    borderRadius: 8,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    gap: 3,
    overflow: "hidden",
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  bracketMatchCardLive: {
    borderColor: "#fecaca",
    backgroundColor: "#fff7f7",
  },
  bracketConnectorLine: {
    width: 26,
    height: 1,
    backgroundColor: "#cbd5e1",
  },
  bracketMatchMeta: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 13,
    textTransform: "uppercase",
  },
  bracketPlayerRow: {
    height: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  bracketPlayerName: {
    flex: 1,
    minWidth: 0,
    color: "#111827",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 16,
  },
  bracketPlayerWinner: {
    color: "#17683a",
  },
  bracketPlayerEliminated: {
    color: "#a52a2a",
  },
  bracketPlayerPending: {
    color: "#6b7280",
  },
  bracketScoreCells: {
    flexDirection: "row",
    flexShrink: 0,
    gap: 2,
  },
  bracketScoreCell: {
    minWidth: 14,
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "900",
    lineHeight: 15,
    textAlign: "center",
  },
  bracketScoreWinner: {
    color: "#17683a",
  },
  matchScoreLive: {
    color: "#dc2626",
  },
  matchScoreCompleted: {
    color: "#067647",
  },
});
